balance:
  amount: 0.0
  date: '2025-01-01'
entity:
  address: ''
  currency: EUR
  logo: ''
  name: Mon Entite
  rna: ''
  siret: ''
  type: association
  vat_enabled: false
modules:
  annotations: true
  attachments: true
  audit: true
  backup: true
  budget: false
  categories: true
  dashboard: true
  entities: true
  export: true
  fec_export: true
  invoices: false
  multi_users: true
  reimbursements: false
  smart_import: true
  system: true
  tiers: false
  transactions: true
