entity:
  name: Test Entity
  type: association
  currency: EUR
  logo: ''
  address: ''
  siret: ''
  rna: ''

balance:
  date: '2025-01-01'
  amount: 0.0

modules:
  entities: true
  transactions: true
  categories: true
  dashboard: true
  reimbursements: true
  budget: true
  tiers: true
  attachments: true
  backup: true
  system: true
  reports: true
  helloasso: true
  bank_reconciliation: true
  treasury: true
  direns: true
  users: true
  submissions: true
