balance:
  amount: 0.0
  date: '2025-01-01'
entity:
  address: ''
  currency: EUR
  logo: ''
  name: Mon Entite
  rna: ''
  siret: ''
  type: association
  vat_enabled: false
modules:
  attachments: true
  backup: true
  budget: false
  categories: true
  dashboard: true
  direns: false
  entities: true
  helloasso: true
  reimbursements: false
  reports: false
  submissions: true
  system: true
  tiers: false
  transactions: true
  users: true
